appenders:
  stdout: 
    kind: console
    encoder: 
      pattern: "{h({l})} - {d(%Y-%m-%d %H:%M:%S)} - {m}\n"
    filters: 
      - kind: threshold
        level: info
  file: 
    kind: file
    path: logs/mm.log
    encoder:
      pattern: "{l} - {d(%Y-%m-%d %H:%M:%S)} - {m}\n"

root: 
  level: debug
  appenders:
    - stdout
    - file